nav:
  Home: /index.html
  Sheet Music: https://arbochelli.me/
  Posts: /posts/
  Donate: /donate/

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /static/favicon.png
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /static/favicon.png
      android:
        url: /static/favicon-192x192.png
      apple:
        url: /static/apple-touch-icon.png
    post_count: 5
    highlight: railscasts

# keept it like this to add the root path (probably a bug)
root: ..

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
